<%@ Page Title="" Language="C#" MasterPageFile="~/PaginaMaestraAdmin.Master" AutoEventWireup="true" CodeBehind="ListarUsuarios.aspx.cs" Inherits="CapaInterfaz.Administrador.ListarUsuarios" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <asp:ScriptManager ID="ScriptManager1" runat="server">
    </asp:ScriptManager>
    <h4>Listar Usuarios</h4>
    <asp:UpdatePanel ID="UpdatePanel1" runat="server">
        <ContentTemplate>
            <asp:Label ID="Label1" runat="server" Text="Ingrese ID :"></asp:Label><asp:TextBox
                ID="txtIdUsuario" runat="server"></asp:TextBox>
            <asp:RegularExpressionValidator ID="RegularExpressionValidator1" runat="server" 
                ControlToValidate="txtIdUsuario" ErrorMessage="Solo Numeros" ForeColor="Red" 
                ValidationExpression="([0-9]|-)*"></asp:RegularExpressionValidator>
            <asp:Button ID="Button1" runat="server" Text="Listar" Width="77px" />
            <br />
            <asp:GridView ID="gvListarUsuarios" runat="server" 
                AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
            </asp:GridView>
        </ContentTemplate>
    </asp:UpdatePanel>
</asp:Content>
