<%@ Page Title="" Language="C#" MasterPageFile="~/PaginaMaestraAdmin.Master" AutoEventWireup="true" CodeBehind="ListarPublicacion.aspx.cs" Inherits="CapaInterfaz.Administrador.ListarPublicacion" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <asp:ScriptManager ID="ScriptManager1" runat="server">
    </asp:ScriptManager>
        <h4>Listar Publicaciones</h4>
    <asp:UpdatePanel ID="UpdatePanel1" runat="server">
        <ContentTemplate>
            <asp:Label ID="Label1" runat="server" Text="Buscar Por ID: "></asp:Label>
            <asp:TextBox ID="txtIdPublicacion" runat="server"></asp:TextBox>
            <asp:RegularExpressionValidator ID="RegularExpressionValidator1" runat="server" 
                ErrorMessage="Solo numeros" ForeColor="Red" 
                ValidationExpression="([0-9]|-)*" ControlToValidate="txtIdPublicacion"></asp:RegularExpressionValidator>
            &nbsp;&nbsp;
            <asp:Button ID="btnListar" runat="server" Text="Listar" Width="84px" 
                onclick="btnListar_Click" />
            <br />
            <asp:GridView ID="gvListarPublicacion" runat="server" AutoGenerateDeleteButton="True" 
                AutoGenerateEditButton="True">
            </asp:GridView>
        </ContentTemplate>
    </asp:UpdatePanel>
</asp:Content>
